### PR TITLE
Rework the Wrapping tutorial and adding the Kubernetes tutorial

### PR DESCRIPTION
**Pull request by splovyt**
I have made some pretty significant changes for the documentation to be more in line with the current implementation. Please review this one before merging @gdequeiroz @SSaishruthi.

Any feedback is welcome. Feel free to reject some of the changes I made as most are suggestions anyways.

### CODE REVIEW

**Comment by SSaishruthi** [comment]
Thanks, @splovyt for the update.

I have added two comments. In addition to that, I had this to do for myself for the readme. Since you have started we can do it here.

Can we move the 4th point to 3rd? This is to make readme in alignment with the video

**Comment by splovyt** [comment]
> Thanks, @splovyt for the update.
> 
> I have added two comments. In addition to that, I had this in mind as one of my to do. Since you have started we can do it here.
> 
> Can we move the 4th point to 3rd? This is to make readme in alignment with the video
> 
> ### Order
> 1. Load model
> 2. Pre-process code
> 3. Model prediction
> 4. Decide on the desired output and update in `label_prediction`
> 5. Post-processing (this will complement the above step - decide then extract)
> 6. Explain about output response
> 7. Update post-processing results to output response
> 
> Let me know what you think about the order

Sure, if you already have the video I will change my order. One question though - do we really need (6) as a separate step? I feel like the explanation can go with another step (e.g. (5) or (7))

**Comment by SSaishruthi** [comment]
4th & 5th 
6th & 7th 

are like pair points. 

It is like deciding with output variables/response and then add the corresponding code.
We can combine 4 with 5 & 6 with 7. I am thinking of having this as a separate step as it may look like too much info under one point.

If you think it will fine, we can go ahead.

**Comment by splovyt** [comment]
I put the Kubernetes tutorial in another file, and use the `max-skeleton.yaml` instead of creating a new file.

I will make the other changes soon.

**Comment by splovyt** [comment]
@SSaishruthi  I have read the wrapping part of the tutorial again, and think it is not too long when we combine points 4-5 and 6-7. It also doesn't read badly in my opinion. Would you mind reviewing it again and letting me know what you think?

**Pull request merged**
